// ============================================
// MediCMS Desktop v4.0 - Mock Data
// For development only - replace with SQLite data
// ============================================

import type { 
  Student, StudentWithBalance, LedgerTransaction, 
  FeeTemplate, Expense, BankTransaction, AuditLog,
  SyncStatus, ImportStep
} from '@/types';
import { getStudentBadge } from './utils';

// --- Mock Students ---
export const MOCK_STUDENTS: Student[] = [
  {
    sno: 41,
    name: 'Waqar Ahmad',
    fatherName: 'Saleem Ullah Khan',
    contact: '+923469044210',
    address: 'Shangla Chakesar',
    cnic: null,
    regDate: '2017-01-05',
    program: 'Pathology',
    course: 'Paramedics',
    batch: '1st Batch',
    session: 2017,
    semester: '3rd',
    struckOff: false,
    isTestRecord: false,
    synced: true,
  },
  {
    sno: 42,
    name: 'Navid Khan',
    fatherName: 'Ahmed Khan',
    contact: '+923001234567',
    address: 'Mingora, Swat',
    cnic: '1560212345671',
    regDate: '2017-01-10',
    program: 'Health',
    course: 'Paramedics',
    batch: '1st Batch',
    session: 2017,
    semester: '3rd',
    struckOff: true,
    struckOffDate: '2018-06-15',
    struckOffReason: 'Non-payment of fees',
    isTestRecord: false,
    synced: true,
  },
  {
    sno: 57,
    name: 'Anwar Ali',
    fatherName: 'Rahim Ali',
    contact: '+923459876543',
    address: 'Kabal, Swat',
    cnic: null,
    regDate: '2017-01-08',
    program: 'Pharmacy',
    course: 'Paramedics',
    batch: '1st Batch',
    session: 2017,
    semester: '3rd',
    struckOff: false,
    isTestRecord: false,
    synced: true,
  },
  {
    sno: 63,
    name: 'Anwar Ali',
    fatherName: 'Khadim Ali',
    contact: '+923449876543',
    address: 'Barikot, Swat',
    cnic: '1560298765432',
    regDate: '2017-01-12',
    program: 'Surgical',
    course: 'Paramedics',
    batch: '1st Batch',
    session: 2017,
    semester: '3rd',
    struckOff: true,
    struckOffDate: '2019-03-20',
    struckOffReason: 'Disciplinary action',
    isTestRecord: false,
    synced: true,
  },
  {
    sno: 76,
    name: 'Sana Ali',
    fatherName: 'Ghulam Ali',
    contact: '+923489464817',
    address: 'Mingora, Swat',
    cnic: '1560234567890',
    regDate: '2017-02-15',
    program: 'Health',
    course: 'Paramedics',
    batch: '2nd Batch',
    session: 2017,
    semester: '3rd',
    struckOff: false,
    isTestRecord: false,
    synced: true,
  },
  {
    sno: 87,
    name: 'Sadiq Noor',
    fatherName: 'Abdul Noor',
    contact: '+923009876543',
    address: 'Khwazakhela, Swat',
    cnic: null,
    regDate: '2019-01-20',
    program: 'Anaesthesia',
    course: 'Paramedics',
    batch: '3rd Batch',
    session: 2019,
    semester: '3rd',
    struckOff: false,
    isTestRecord: false,
    synced: true,
  },
  {
    sno: 99,
    name: 'Anwar Ali',
    fatherName: 'Moula Dad',
    contact: '+923489464817',
    address: 'Charbagh, Swat',
    cnic: '1560245678901',
    regDate: '2017-03-10',
    program: 'Surgical',
    course: 'Paramedics',
    batch: '2nd Batch',
    session: 2017,
    semester: '2nd',
    struckOff: false,
    isTestRecord: false,
    synced: true,
  },
  {
    sno: 114,
    name: 'Amjad Khan',
    fatherName: 'Sher Khan',
    contact: '+923445678901',
    address: 'Matta, Swat',
    cnic: null,
    regDate: '2017-04-05',
    program: 'Health',
    course: 'Paramedics',
    batch: '2nd Batch',
    session: 2017,
    semester: '3rd',
    struckOff: true,
    struckOffDate: '2019-08-10',
    struckOffReason: 'Non-payment of fees',
    isTestRecord: false,
    synced: true,
  },
  {
    sno: 139,
    name: 'Naeem Ullah',
    fatherName: 'Fazal Ullah',
    contact: '+923445678902',
    address: 'Mingora, Swat',
    cnic: '1560256789012',
    regDate: '2017-05-15',
    program: 'Dental',
    course: 'Paramedics',
    batch: '2nd Batch',
    session: 2017,
    semester: '3rd',
    struckOff: false,
    isTestRecord: false,
    synced: true,
  },
  {
    sno: 146,
    name: 'Director Sb',
    fatherName: 'Test',
    contact: null,
    address: null,
    cnic: null,
    regDate: '2017-01-01',
    program: 'Health',
    course: 'Paramedics',
    batch: '1st Batch',
    session: 2017,
    semester: '1st',
    struckOff: false,
    isTestRecord: true,  // Test record
    synced: true,
  },
  {
    sno: 501,
    name: 'Maria Khan',
    fatherName: 'Nawab Khan',
    contact: '+923451234501',
    address: 'Mingora, Swat',
    cnic: null,
    regDate: '2026-03-10',
    program: 'BSN',
    course: 'BSN',
    batch: '17th Batch',
    session: 2026,
    semester: '1st',
    struckOff: false,
    isTestRecord: false,
    synced: true,
  },
  {
    sno: 502,
    name: 'Fatima Bibi',
    fatherName: 'Zafar Ali',
    contact: '+923451234502',
    address: 'Kabal, Swat',
    cnic: null,
    regDate: '2026-03-12',
    program: 'LHV',
    course: 'PNC',
    batch: '17th Batch',
    session: 2026,
    semester: '1st',
    struckOff: false,
    isTestRecord: false,
    synced: true,
  },
  {
    sno: 503,
    name: 'Bilal Ahmad',
    fatherName: 'Said Ahmad',
    contact: '+923451234503',
    address: 'Saidu Sharif, Swat',
    cnic: null,
    regDate: '2026-03-14',
    program: 'Ultrasound1Y',
    course: 'Ultrasound',
    batch: '17th Batch',
    session: 2026,
    semester: '1st',
    struckOff: false,
    isTestRecord: false,
    synced: true,
  },
  {
    sno: 504,
    name: 'Kamran Shah',
    fatherName: 'Habib Shah',
    contact: '+923451234504',
    address: 'Barikot, Swat',
    cnic: null,
    regDate: '2026-03-16',
    program: 'PharmacyB',
    course: 'PharmacyB',
    batch: '17th Batch',
    session: 2026,
    semester: '1st',
    struckOff: false,
    isTestRecord: false,
    synced: true,
  },
];

// --- Mock Ledger Transactions ---
export const MOCK_LEDGER: LedgerTransaction[] = [
  // SNO 76 - Sana Ali (has dues)
  {
    id: 'tx-76-1',
    studentSno: 76,
    txnNo: 1,
    date: '2017-01-15',
    type: 'Demand',
    semester: '1st',
    session: 2017,
    fees: 33700,
    discount: 0,
    payment: 0,
    receiptNo: null,
    receivedBy: null,
    narration: 'This is Registration Time Balance',
    createdAt: '2017-01-15T10:00:00',
    createdBy: 'Admin',
    synced: true,
  },
  {
    id: 'tx-76-2',
    studentSno: 76,
    txnNo: 2,
    date: '2017-01-20',
    type: 'Pay',
    semester: '1st',
    session: 2017,
    fees: 0,
    discount: 14500,
    payment: 12700,
    receiptNo: '#101',
    receivedBy: 'Admin Khalid',
    narration: '',
    createdAt: '2017-01-20T14:30:00',
    createdBy: 'Admin Khalid',
    synced: true,
  },
  {
    id: 'tx-76-3',
    studentSno: 76,
    txnNo: 3,
    date: '2017-03-15',
    type: 'Demand',
    semester: '3rd',
    session: 2018,
    fees: 27000,
    discount: 0,
    payment: 0,
    receiptNo: null,
    receivedBy: null,
    narration: 'This is Next Promote Semester Fees',
    createdAt: '2018-03-15T09:00:00',
    createdBy: 'Admin Khalid',
    synced: true,
  },
  {
    id: 'tx-76-4',
    studentSno: 76,
    txnNo: 4,
    date: '2018-03-20',
    type: 'Pay',
    semester: '3rd',
    session: 2018,
    fees: 0,
    discount: 5000,
    payment: 14100,
    receiptNo: '#251',
    receivedBy: 'Admin Khalid',
    narration: '',
    createdAt: '2018-03-20T11:00:00',
    createdBy: 'Admin Khalid',
    synced: true,
  },
];

// --- Mock Fee Templates ---
export const MOCK_FEE_TEMPLATES: FeeTemplate[] = [
  {
    id: 'tpl-health-1-2017',
    program: 'Health',
    course: 'Paramedics',
    semester: '1st',
    batch: '1st Batch',
    session: 2017,
    admissionFee: 15000,
    tuitionFee: 15000,
    idCardFee: 200,
    annualCharges: 0,
    securityFee: 0,
    enrollmentFee: 5000,
    diplomaFee: 0,
    clinicalCharges: 0,
  },
  {
    id: 'tpl-health-3-2017',
    program: 'Health',
    course: 'Paramedics',
    semester: '3rd',
    batch: '1st Batch',
    session: 2018,
    admissionFee: 0,
    tuitionFee: 15000,
    idCardFee: 0,
    annualCharges: 1000,
    securityFee: 0,
    enrollmentFee: 0,
    diplomaFee: 0,
    clinicalCharges: 11000,
  },
  {
    id: 'tpl-anaesthesia-1-2019',
    program: 'Anaesthesia',
    course: 'Paramedics',
    semester: '1st',
    batch: '3rd Batch',
    session: 2019,
    admissionFee: 20000,
    tuitionFee: 20000,
    idCardFee: 0,
    annualCharges: 0,
    securityFee: 0,
    enrollmentFee: 5000,
    diplomaFee: 0,
    clinicalCharges: 0,
  },
  {
    id: 'tpl-bsn-1-2026',
    program: 'BSN',
    course: 'BSN',
    semester: '1st',
    batch: '17th Batch',
    session: 2026,
    admissionFee: 30000,
    tuitionFee: 40000,
    idCardFee: 300,
    annualCharges: 0,
    securityFee: 5000,
    enrollmentFee: 0,
    diplomaFee: 0,
    clinicalCharges: 0,
  },
  {
    id: 'tpl-lhv-1-2026',
    program: 'LHV',
    course: 'PNC',
    semester: '1st',
    batch: '17th Batch',
    session: 2026,
    admissionFee: 10000,
    tuitionFee: 15000,
    idCardFee: 200,
    annualCharges: 0,
    securityFee: 0,
    enrollmentFee: 5000,
    diplomaFee: 0,
    clinicalCharges: 0,
  },
  {
    id: 'tpl-ultrasound1y-1-2026',
    program: 'Ultrasound1Y',
    course: 'Ultrasound',
    semester: '1st',
    batch: '17th Batch',
    session: 2026,
    admissionFee: 12000,
    tuitionFee: 25000,
    idCardFee: 200,
    annualCharges: 0,
    securityFee: 0,
    enrollmentFee: 0,
    diplomaFee: 0,
    clinicalCharges: 0,
  },
  {
    id: 'tpl-pharmacyb-1-2026',
    program: 'PharmacyB',
    course: 'PharmacyB',
    semester: '1st',
    batch: '17th Batch',
    session: 2026,
    admissionFee: 15000,
    tuitionFee: 20000,
    idCardFee: 200,
    annualCharges: 0,
    securityFee: 0,
    enrollmentFee: 5000,
    diplomaFee: 0,
    clinicalCharges: 0,
  },
];

// --- Mock Expenses ---
export const MOCK_EXPENSES: Expense[] = [
  {
    id: 'exp-5',
    category: 'SAL',
    amount: 54500,
    date: '2020-04-30',
    time: '14:00',
    givenBy: 'M.Sharif',
    details: 'Staff salaries for April 2020',
    bankTransactionId: 'bank-3',
    synced: true,
  },
  {
    id: 'exp-6',
    category: 'FOOD',
    amount: 11060,
    date: '2020-04-30',
    time: '16:30',
    givenBy: 'Director',
    details: 'Refreshments',
    bankTransactionId: null,
    synced: true,
  },
  {
    id: 'exp-7',
    category: 'UTIL',
    amount: 4990,
    date: '2020-05-14',
    time: '10:00',
    givenBy: 'Director',
    details: 'Electricity bill',
    bankTransactionId: null,
    synced: true,
  },
];

// --- Mock Bank Transactions ---
export const MOCK_BANK: BankTransaction[] = [
  { sno: 1, date: '2019-03-01', deposit: 41500, withdrawal: 0, balance: 53460, narration: 'Fee collection', linkedExpenseId: null, isPersonal: false, synced: true },
  { sno: 2, date: '2020-05-12', deposit: 0, withdrawal: 53460, balance: 0, narration: 'Salary payment', linkedExpenseId: 'exp-5', isPersonal: false, synced: true },
  { sno: 3, date: '2020-05-12', deposit: 95635, withdrawal: 0, balance: 95635, narration: 'Fee collection', linkedExpenseId: null, isPersonal: false, synced: true },
  { sno: 4, date: '2021-02-17', deposit: 1321405, withdrawal: 0, balance: 1325540, narration: 'Large deposit', linkedExpenseId: null, isPersonal: false, synced: true },
  { sno: 5, date: '2021-05-24', deposit: 0, withdrawal: 45000, balance: 1227840, narration: 'Director giving to nephew as lend', linkedExpenseId: null, isPersonal: true, synced: true },
  { sno: 6, date: '2021-07-02', deposit: 0, withdrawal: 452400, balance: 547940, narration: 'Withdrawal', linkedExpenseId: null, isPersonal: false, synced: true },
];

// --- Mock Audit Logs ---
export const MOCK_AUDIT: AuditLog[] = [
  {
    id: 'audit-1',
    timestamp: '2026-03-23T10:35:00',
    user: 'Admin Khalid',
    action: 'Payment',
    studentSno: 99,
    details: 'PKR 22,200 · Rcpt #853',
    synced: true,
  },
  {
    id: 'audit-2',
    timestamp: '2026-03-23T10:20:00',
    user: 'Admin Khalid',
    action: 'Student Edit',
    studentSno: 41,
    details: 'Contact changed',
    changes: [{ field: 'Contact', before: '+923469044210', after: '+923001234567' }],
    synced: true,
  },
  {
    id: 'audit-3',
    timestamp: '2026-03-23T09:45:00',
    user: 'Admin Khalid',
    action: 'New Admission',
    studentSno: 141,
    details: 'Bilal Ahmad · Radiology · 17th Batch',
    synced: true,
  },
  {
    id: 'audit-4',
    timestamp: '2026-03-22T16:00:00',
    user: 'Admin Khalid',
    action: 'Struck Off',
    studentSno: 42,
    details: 'Reason: Non-payment of fees',
    synced: true,
  },
];

// --- Mock Sync Status ---
export const MOCK_SYNC_STATUS: SyncStatus = {
  status: 'online',
  lastSync: '2026-03-23T10:42:00',
  pendingCount: 0,
};

// --- Mock Import Steps ---
export const MOCK_IMPORT_STEPS: ImportStep[] = [
  { id: 'students', name: 'Import Students', status: 'completed', recordsCount: 100 },
  { id: 'templates', name: 'Import Fee Templates', status: 'completed', recordsCount: 48 },
  { id: 'ledger', name: 'Map Ledger → Students', status: 'warning', recordsCount: 87, warnings: ['11 unmatched student IDs'] },
  { id: 'bank', name: 'Import Bank Ledger', status: 'completed', recordsCount: 24 },
  { id: 'expenses', name: 'Import Expenses', status: 'completed', recordsCount: 5 },
  { id: 'verify', name: 'Verify & Confirm', status: 'pending' },
];

// --- Mock Dashboard Stats ---
export const MOCK_DASHBOARD = {
  activeStudents: 484,
  struckOffStudents: 35,
  totalDues: 482000,
  pendingSync: 3,
  todayPayments: [
    { receiptNo: '#853', name: 'Anwar A', amount: 22200 },
    { receiptNo: '#854', name: 'Bilal K', amount: 10000 },
    { receiptNo: '#855', name: 'Azmat A', amount: 10200 },
  ],
  topDefaulters: [
    { sno: 87, name: 'Sadiq Noor', program: 'Anaesthesia', dues: 27000 },
    { sno: 76, name: 'Sana Ali', program: 'Health', dues: 23100 },
    { sno: 88, name: 'Anwar Zeb', program: 'Pharmacy', dues: 20000 },
    { sno: 122, name: 'Faisal A', program: 'Anaesthesia', dues: 20000 },
    { sno: 97, name: 'M. Jamil', program: 'Surgical', dues: 16000 },
  ],
};

// --- Student balances (computed from the ledger in the real app) ---
export const MOCK_BALANCES: Record<number, number> = {
  41: 0,
  42: 5000,
  57: 0,
  63: 0,
  76: 23100,
  87: 27000,
  99: 11500,
  114: -20000,  // Credit
  139: -12500,  // Credit
  146: 0,
};

export function getStudentBalance(sno: number): number {
  return MOCK_BALANCES[sno] ?? 0;
}

// --- Helper: Get students with computed balance ---
export function getStudentsWithBalance(students: Student[] = MOCK_STUDENTS): StudentWithBalance[] {
  return students.map(student => {
    const balance = getStudentBalance(student.sno);
    return {
      ...student,
      computedBalance: balance,
      badge: getStudentBadge(student.struckOff, balance),
    };
  });
}
